export BASH_SILENCE_DEPRECATION_WARNING=1
export PS1="\u@\h:\w$ "
export PS1="${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ "

export EDITOR=vim

[[ -s "$HOME/.profile" ]] && source "$HOME/.profile" # Load the default .profile

[[ -s "$HOME/bin" ]] && export PATH="$PATH:$HOME/bin"

if [ command -v brew ]; then
  if [ -f $(brew --prefix)/etc/bash_completion ]; then
    . $(brew --prefix)/etc/bash_completion
  fi
fi

eval "$(nodenv init -)"

export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

source /usr/local/etc/bash_completion.d/git-completion.bash

alias dce="docker-compose exec"
export PATH="/usr/local/opt/libxml2/bin:$PATH"

# Generated by Strap - PATH
export PATH=/usr/local/opt/mysql-client@5.7/bin:$PATH

# Generated by Strap - PUMADEV_SOURCE_ENV
export PUMADEV_SOURCE_ENV=0
